osx_image: xcode8.0
language: objective-c
script:
- set -o pipefail && xcodebuild -workspace ios-swift/encryptor-swift.xcworkspace -scheme encryptor-swift -sdk iphonesimulator10.0 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
