language: objective-c
osx_image: xcode8
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace ios-swift/encryptor-swift.xcworkspace -scheme encryptor-swift -sdk iphonesimulator10.0 -configuration Release ONLY_ACTIVE_ARCH=NO build