osx_image: xcode8.0
language: swift
script:
- set -o pipefail && xcodebuild encryptor-swift -workspace ios-swift/encryptor-swift.xcworkspace -scheme encryptor-swift -sdk iphonesimulator10.0 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint